services:
  postgres:
    image: postgres:16
    container_name: project-postgres
    environment:
      POSTGRES_DB: projectDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - project_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d projectDb"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
    container_name: devices-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: projectDb
      DB_USER: admin
      DB_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  project_postgres_data:
