services:
  postgres:
    image: postgres:16
    container_name: project-postgres
    environment:
      POSTGRES_DB: projectDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - project_postgres_data:/var/lib/postgresql/data

volumes:
  project_postgres_data:
